name: generate ASCII with script
on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Executing shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh