name:  Multiple Job
on: push
jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:

            - name: install cowyay
              run: sudo apt-get install cowsay -y
            - name: generate 
              run: |
                cowsay -f dragon "run for cover , I am dragon RAWR ...." >> dragon1.txt

              