name: Using job concurrency
on:
    workflow_dispatch:
 # schedule:
 #   - cron: "*/1 * * * *"
env: 
    CONTAINER_REGISTRY: docker.io
    DOCKER_IMAGE: github-actions-nginx
jobs:
        docker:
            runs-on: ubuntu-latest
            steps:
                - name: docker build  
                  run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE
                - name: docker login
                  run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
                - name: docker publish 
                  run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE
    
        deploy: 
    
            needs: docker
            runs-on: ubuntu-latest
            steps:
                
                - name: docker run
                  run: |
                    echo docker run $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE
                    sleep 600

