name: exporing variables and sescret
on: push
env: 
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: akaliza
    DOCKER_IMAGE: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build  
              run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE
            - name: docker login
              env: 
                DOCKER_PASSWORD: pass
              run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}
            - name: docker publish 
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE

    deploy: 

        needs: docker
        runs-on: ubuntu-latest
        steps:
            
            - name: docker run
              run: docker run $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE
