name: exploring filters
on: 
  forkflow_dispatch:
  #schedule:
  #- cron: "*/25 * * * *"
  push:
    branches:
    - main
    - '!feature/*'
    #branches-ignore:
    #- feature/*
    #- test/**
  pull_request: 
    types:
    - opened
    - closed
    paths-ignore:
    - README.md
    branches: 
    - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: "when the job was executed - event type"
      run: echo when the job was executed - event type run -  ${{ github.event_name }} 